import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      items: [
        "intro",
        "architecture",
        "supported-engines",
        "data-collection-and-privacy",
        "security-model",
      ],
    },
    {
      type: "category",
      label: "Setup",
      items: [
        "getting-started",
        "agent-installation",
        "agent-configuration",
        "api-keys",
        "managed-targets",
      ],
    },
    {
      type: "category",
      label: "Database Engines",
      items: [
        "engines/postgresql",
        "engines/mssql",
        "engines/mongodb",
        "engines/redis-valkey",
        "engines/oracle",
      ],
    },
    {
      type: "category",
      label: "Product Guides",
      items: [
        {
          type: "category",
          label: "Database Explorer",
          link: { type: "doc", id: "product-guides/database-explorer/index" },
          items: [
            "product-guides/database-explorer/overview",
            "product-guides/database-explorer/schema",
          ],
        },
        {
          type: "category",
          label: "Activity Explorer",
          link: { type: "doc", id: "product-guides/activity-explorer/index" },
          items: [
            "product-guides/activity-explorer/overview",
            "product-guides/activity-explorer/connections",
            "product-guides/activity-explorer/wait-events",
            "product-guides/activity-explorer/blocking-chains",
            "product-guides/activity-explorer/wait-activity",
          ],
        },
        {
          type: "category",
          label: "Query Explorer",
          link: { type: "doc", id: "product-guides/query-explorer/index" },
          items: [
            "product-guides/query-explorer/overview",
            "product-guides/query-explorer/statistics",
          ],
        },
        {
          type: "category",
          label: "Schema Explorer",
          link: { type: "doc", id: "product-guides/schema-explorer/index" },
          items: [
            "product-guides/schema-explorer/overview",
            "product-guides/schema-explorer/changes",
            "product-guides/schema-explorer/permissions",
          ],
        },
        "product-guides/alerts",
        "product-guides/insights",
        "product-guides/data-inventory",
        "product-guides/assets",
        "product-guides/integrations",
        "product-guides/audit-logs",
      ],
    },
    {
      type: "category",
      label: "Operations",
      items: [
        "operations/troubleshooting",
        "operations/agent-logs",
        "operations/upgrades",
        "operations/performance-and-interval-tuning",
      ],
    },
  ],
};

export default sidebars;
